"""One-time migration: rebuild data/theme-log.json from the old
{week: {signs: {theme, note}}} shape into the extended per-sign-per-week
schema (schema_version 2), backfilling full weekly-observation detail
for 2026-07-20, 2026-07-27, 2026-08-03, and 2026-08-10 from the digest
JSONs as they existed in git history at each week's release commit
(digest_<sign>_week1.json is overwritten every week, so historical
content only survives in past commits).

Usage: python3 backfill_theme_log.py

Refuses to run if data/theme-log.json is already schema_version 2 (the
new pipeline appends to that file directly; re-running this migration
would either duplicate work or clobber entries it can't reconstruct).

Reports missing/unexpected data instead of silently writing nulls.
"""
import json
import subprocess
import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent
THEME_LOG_PATH = BASE_DIR / "data" / "theme-log.json"

CATEGORIES = ["love", "finance", "career", "family"]
SIGNS = [
    "aries", "taurus", "gemini", "cancer", "leo", "virgo",
    "libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces",
]

# The commit that holds each week's digest_<sign>_week1.json content, picked
# as the last commit where that file's week_of matches the target week
# before the next week's run overwrote it (19ff60a briefly mislabeled
# 2026-07-27 as "2026-07-29"; 4e865b3 is the fix, so it's used instead).
WEEK_COMMITS = {
    "2026-07-20": "8e13e53",
    "2026-07-27": "4e865b3",
    "2026-08-03": "fde117e",
    "2026-08-10": "fa87105",
}

REPEATS_ALLOWED_FROM = "2026-08-17"

# Known, human-reviewed gaps in the historical source data itself (not
# backfill bugs). Each is (sign, week_of, video_id, field) and is written as
# null rather than aborting the run. Anything else missing still aborts.
KNOWN_GAPS = {
    ("capricorn", "2026-07-27", "ID5u08xuJac", "channel_theme"),
}

NOTES = {
    "theme": (
        "Aggregate one-word mood for the sign's whole week. Drawn from the "
        "fixed THEME_VOCABULARY in aggregate_digest.py (cautious, hopeful, "
        "restless, transformative, reflective, empowering, turbulent, "
        "liberating). While theme_rule='no-repeat-4wk', cannot repeat any "
        "theme used in this sign's prior 4 weeks. From theme_rule="
        "'repeats-allowed' (2026-08-17 on), the full vocabulary is "
        "available every week; the sign's own recent history is shown to "
        "the model as context only, not an exclusion list, and the choice "
        "is based purely on that week's 5 readings."
    ),
    "reader_tone": (
        "One-word tone tag for a single reading, assigned during tagging "
        "(tag_transcripts.py's overall_tone field). Free-form vocabulary, "
        "NOT constrained to THEME_VOCABULARY, not to be confused with "
        "`theme`."
    ),
    "agreement": (
        "Integer 0-5: how many of the 5 readers the aggregating model "
        "judged to have touched on / discussed a theme similar in meaning "
        "to this category's summary. This is a coverage count, not a "
        "directional-consensus count: two readers can both be counted here "
        "even if they took opposite positions (e.g. one predicts reunion, "
        "one predicts ending). Such conflicts are captured separately in "
        "`divergence`."
    ),
    "divergence": (
        "Notable disagreement between readers on this category, in the "
        "aggregating model's words. Null when it found no notable "
        "disagreement (placeholder phrases like 'No notable disagreement "
        "among readers...' are normalized to null rather than kept as text)."
    ),
    "repeat_streak": (
        "Number of consecutive most-recent weeks (including this one) this "
        "sign's theme has stayed the same. Always 1 for every entry through "
        "2026-08-10: theme_rule='no-repeat-4wk' forbids reusing any theme "
        "from the prior 4 weeks, so a back-to-back repeat was structurally "
        "impossible in that window. This is an artifact of the exclusion "
        "rule, not a signal that themes were volatile. From 2026-08-17, "
        "increments by 1 when the new theme matches the immediately "
        "preceding week's theme, and resets to 1 otherwise. Whenever "
        "repeat_streak >= 2, overall_tone_summary states this plainly and "
        "factually (e.g. 'Second week running.')."
    ),
    "theme_rule": (
        "Which exclusion rule was in effect when `theme` was assigned: "
        "'no-repeat-4wk' (weeks through 2026-08-10) or 'repeats-allowed' "
        f"({REPEATS_ALLOWED_FROM} on)."
    ),
    "category_tone_gap": (
        "Per-category (love/finance/career/family) tone was never "
        "generated by the pipeline, only reader_tone (per-reading) and "
        "theme (per-sign aggregate) exist. No `tone` key is included inside "
        "category objects."
    ),
    "channel_name_gap": (
        "Reader channel names were never captured by the pipeline (only "
        "video_id, url, and paraphrased content). No `channel_name` key is "
        "included in reader objects."
    ),
}


def is_placeholder_disagreement(text):
    if not text:
        return True
    lowered = text.lower()
    return "no notable disagreement" in lowered or "no strong disagreement" in lowered


def load_digest_at_commit(commit: str, sign: str) -> dict:
    path = f"digest_{sign}_week1.json"
    result = subprocess.run(
        ["git", "show", f"{commit}:{path}"],
        cwd=BASE_DIR, capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git show {commit}:{path} failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


def build_entry(digest: dict, sign_slug: str, week_of: str, theme_rule: str, repeat_streak: int, missing: list, flagged: list) -> dict:
    if digest["week_of"] != week_of:
        missing.append(f"{sign_slug}/{week_of}: digest week_of mismatch (found {digest['week_of']!r})")

    categories = {}
    for cat in CATEGORIES:
        c = digest["categories"].get(cat)
        if c is None:
            missing.append(f"{sign_slug}/{week_of}: category '{cat}' missing entirely")
            continue
        for field in ("summary", "reader_count"):
            if c.get(field) is None:
                missing.append(f"{sign_slug}/{week_of}/{cat}: '{field}' is missing/null")
        categories[cat] = {
            "summary": c.get("summary"),
            "agreement": c.get("reader_count"),
            "divergence": None if is_placeholder_disagreement(c.get("disagreement")) else c.get("disagreement"),
        }

    readers = []
    reader_list = digest.get("readers", [])
    if len(reader_list) != 5:
        missing.append(f"{sign_slug}/{week_of}: expected 5 readers, found {len(reader_list)}")
    for r in reader_list:
        video_id = r.get("video_id", "?")
        for field in ("video_id", "url", "channel_theme", "tone"):
            if not r.get(field):
                gap_key = (sign_slug, week_of, video_id, field)
                if gap_key in KNOWN_GAPS:
                    flagged.append(f"{sign_slug}/{week_of}/{video_id}: '{field}' is blank in the original source data, written as null (known, reviewed gap)")
                else:
                    missing.append(f"{sign_slug}/{week_of}/{video_id}: '{field}' is missing/empty")
        readers.append({
            "video_id": r.get("video_id"),
            "url": r.get("url"),
            "distinctive_point": r.get("channel_theme") or None,
            "reader_tone": r.get("tone"),
        })

    if digest.get("overall_tone") is None:
        missing.append(f"{sign_slug}/{week_of}: overall_tone is missing/null")
    if digest.get("overall_tone_summary") is None:
        missing.append(f"{sign_slug}/{week_of}: overall_tone_summary is missing/null")

    return {
        "week_of": week_of,
        "sign": sign_slug,
        "theme": digest.get("overall_tone"),
        "theme_rule": theme_rule,
        "repeat_streak": repeat_streak,
        "overall_tone_summary": digest.get("overall_tone_summary"),
        "categories": categories,
        "readers": readers,
    }


def main():
    if THEME_LOG_PATH.exists():
        existing = json.loads(THEME_LOG_PATH.read_text(encoding="utf-8"))
        if isinstance(existing, dict) and existing.get("schema_version") == 2:
            print(
                f"ERROR: {THEME_LOG_PATH} is already schema_version 2. "
                "Refusing to re-run this one-time migration over it; the live "
                "pipeline (aggregate_digest.py) owns appends from here on."
            )
            return 1

    weeks = sorted(WEEK_COMMITS.keys())
    missing = []
    flagged = []
    entries = []
    streak_state = {}  # sign -> (last_theme, streak)

    for week_of in weeks:
        commit = WEEK_COMMITS[week_of]
        theme_rule = "no-repeat-4wk" if week_of < REPEATS_ALLOWED_FROM else "repeats-allowed"
        for sign in SIGNS:
            try:
                digest = load_digest_at_commit(commit, sign)
            except RuntimeError as e:
                missing.append(str(e))
                continue

            theme = digest.get("overall_tone")
            last_theme, streak = streak_state.get(sign, (None, 0))
            streak = streak + 1 if theme == last_theme else 1
            streak_state[sign] = (theme, streak)

            entry = build_entry(digest, sign, week_of, theme_rule, streak, missing, flagged)
            entries.append(entry)

    print(f"Built {len(entries)} entries across {len(weeks)} weeks x {len(SIGNS)} signs.")

    if flagged:
        print(f"\n{len(flagged)} KNOWN GAP(S) in source data, written as null:")
        for f in flagged:
            print(f"  - {f}")

    if missing:
        print(f"\n{len(missing)} MISSING/UNEXPECTED ITEM(S), not silently filled:")
        for m in missing:
            print(f"  - {m}")
        print("\nRefusing to write output while unresolved gaps exist. Review above.")
        return 1

    output = {
        "schema_version": 2,
        "notes": NOTES,
        "entries": entries,
    }
    THEME_LOG_PATH.write_text(json.dumps(output, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWrote {THEME_LOG_PATH} ({len(entries)} entries).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
